name: open_dev
description: "Open source cross-platform developer assistance"

version: 0.0.1+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.1
  dio: ^5.4.1
  easy_sidemenu: ^0.6.0
  re_editor: ^0.3.0
  re_highlight: ^0.0.3
  flutter_acrylic: ^1.1.3
  xml: ^6.5.0
  xml2json: ^6.2.3
  yaml_edit: ^2.2.0
  cron_expression_descriptor: ^0.9.0
  cron_parser: ^0.5.0
  intl: ^0.19.0
  markdown_widget: ^2.3.2+6
  html: ^0.15.4
  file_picker: ^8.0.2
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
