name: open_dev
description: "Open source cross-platform developer assistant"

version: 0.5.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.2.1
  dio: ^5.4.1
  easy_sidemenu: ^0.6.0
  re_editor: ^0.3.0
  re_highlight: ^0.0.3
  flutter_acrylic: ^1.1.4
  window_manager: ^0.3.9
  xml: ^6.5.0
  xml2json: ^6.2.3
  yaml_edit: ^2.2.0
  cron_expression_descriptor: ^0.9.0
  cron_parser: ^0.5.0
  intl: ^0.19.0
  markdown_widget: ^2.3.2+6
  html: ^0.15.4
  file_picker: ^8.0.2
  dart_jsonwebtoken: ^2.14.0
  crypto: ^3.0.3
  flutter_colorpicker: ^1.1.0
  flutter_color_models: ^1.3.3+2
  pretty_qr_code: ^3.3.0
  image: ^4.2.0
  url_launcher: ^6.3.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/icon.png"

msix_config:
  display_name: Open Dev
  publisher_display_name: Mohada
  identity_name: com.mohada.openDev
  msix_version: 0.5.0.0
  logo_path: assets/logo/icon.png
  capabilities: internetClient

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
